show index from CTCB_project;
show index from CTCB_data1;
show index from CTCB_hdf5_prod;
show index from CTCB_home;
show index from CTCB_mpData;
show index from CTCB_omicsoft;
show index from CTCB_scratch;
show index from CTCB_store_prod;
show index from CTCB_store_test;
